package pn;
import java.math.BigDecimal;
import org.oristool.models.pn.PostUpdater;
import org.oristool.models.pn.Priority;
import org.oristool.models.stpn.MarkingExpr;
import org.oristool.models.stpn.trees.StochasticTransitionFeature;
import org.oristool.petrinet.EnablingFunction;
import org.oristool.petrinet.Marking;
import org.oristool.petrinet.PetriNet;
import org.oristool.petrinet.Place;
import org.oristool.petrinet.Transition;

public class PN_TrainCoupling_simple extends PN_TrainCoupling{
	
	public static void main(String[] args) {
		PetriNet net = new PetriNet();
		Marking marking = new Marking();
		build(net, marking);
		System.out.println("Ok");
	}
	
	public static void build(PetriNet net, Marking marking) {

	    //Generating Nodes
	    Place c1 = net.addPlace("c1");
	    Place c2 = net.addPlace("c2");
	    Place cWait1 = net.addPlace("cWait1");
	    Place cWait2 = net.addPlace("cWait2");
	    Place couples1 = net.addPlace("couples1");
	    Place couples2 = net.addPlace("couples2");
	    Place d1 = net.addPlace("d1");
	    Place d2 = net.addPlace("d2");
	    Place dWait1 = net.addPlace("dWait1");
	    Place dWait2 = net.addPlace("dWait2");
	    Place decoupled1 = net.addPlace("decoupled1");
	    Place decoupled2 = net.addPlace("decoupled2");
	    Place decouples1 = net.addPlace("decouples1");
	    Place decouples2 = net.addPlace("decouples2");
	    Place e1 = net.addPlace("e1");
	    Place e1_dec = net.addPlace("e1_dec");
	    Place e2 = net.addPlace("e2");
	    Place e2_dec = net.addPlace("e2_dec");
	    Place in1 = net.addPlace("in1");
	    Place in2 = net.addPlace("in2");
	    Place out1 = net.addPlace("out1");
	    Place out2 = net.addPlace("out2");
	    Place preC1 = net.addPlace("preC1");
	    Place preC2 = net.addPlace("preC2");
	    Place ready1 = net.addPlace("ready1");
	    Place ready2 = net.addPlace("ready2");
	    Place sS1 = net.addPlace("s1");
	    Place sS2 = net.addPlace("s2");
	    Place sem = net.addPlace("sem");
	    Place slaves1 = net.addPlace("slaves1");
	    Place slaves2 = net.addPlace("slaves2");
	    Transition arrivals1 = net.addTransition("arrivals1");
	    Transition arrivals2 = net.addTransition("arrivals2");
	    Transition c1ToD1 = net.addTransition("c1ToD1");
	    Transition c2ToD2 = net.addTransition("c2ToD2");
	    Transition couple1 = net.addTransition("couple1");
	    Transition couple2 = net.addTransition("couple2");
	    Transition d1ToE1 = net.addTransition("d1ToE1");
	    Transition d1ToE1_dec = net.addTransition("d1ToE1_dec");
	    Transition d2ToE2 = net.addTransition("d2ToE2");
	    Transition d2ToE2_dec = net.addTransition("d2ToE2_dec");
	    Transition decouple1 = net.addTransition("decouple1");
	    Transition decouple2 = net.addTransition("decouple2");
	    Transition masterEnter1 = net.addTransition("masterEnter1");
	    Transition masterEnter2 = net.addTransition("masterEnter2");
	    Transition preCouple1 = net.addTransition("preCouple1");
	    Transition preCouple2 = net.addTransition("preCouple2");
	    Transition s1ToC1 = net.addTransition("s1ToC1");
	    Transition s2ToC2 = net.addTransition("s2ToC2");
	    Transition slaveEnter1 = net.addTransition("slaveEnter1");
	    Transition slaveEnter2 = net.addTransition("slaveEnter2");
	    Transition toC1 = net.addTransition("toC1");
	    Transition toC2 = net.addTransition("toC2");
	    Transition toD1 = net.addTransition("toD1");
	    Transition toD2 = net.addTransition("toD2");
	    Transition toOut1 = net.addTransition("toOut1");
	    Transition toOut1_dec = net.addTransition("toOut1_dec");
	    Transition toOut2 = net.addTransition("toOut2");
	    Transition toOut2_dec = net.addTransition("toOut2_dec");
	    Transition toReady1 = net.addTransition("toReady1");
	    Transition toReady2 = net.addTransition("toReady2");

	    //Generating Connectors
	    net.addPostcondition(toReady2, ready2);
	    net.addPrecondition(slaves2, slaveEnter2);
	    net.addPostcondition(preCouple2, c2);
	    net.addPrecondition(d1, decouple1);
	    net.addPrecondition(preC2, preCouple2);
	    net.addPrecondition(sem, masterEnter1);
	    net.addPostcondition(slaveEnter2, sS2);
	    net.addPostcondition(masterEnter2, sS2);
	    net.addPrecondition(sem, masterEnter2);
	    net.addPostcondition(c2ToD2, d2);
	    net.addPrecondition(dWait1, toD1);
	    net.addPostcondition(c1ToD1, d1);
	    net.addPostcondition(toC1, c1);
	    net.addPostcondition(couple1, cWait1);
	    net.addPostcondition(toOut2, out2);
	    net.addPostcondition(arrivals2, in2);
	    net.addPostcondition(toC2, c2);
	    net.addPrecondition(couples2, toC2);
	    net.addPrecondition(in2, masterEnter2);
	    net.addPrecondition(dWait2, toD2);
	    net.addPrecondition(ready1, c1ToD1);
	    net.addPrecondition(couples1, toC1);
	    net.addPrecondition(sS2, s2ToC2);
	    net.addPostcondition(decouple1, decoupled1);
	    net.addPostcondition(masterEnter1, sS1);
	    net.addPrecondition(in1, masterEnter1);
	    net.addPrecondition(dWait2, d2ToE2);
	    net.addPostcondition(toOut2, sem);
	    net.addPostcondition(toOut1, sem);
	    net.addPrecondition(sS1, s1ToC1);
	    net.addPrecondition(in1, slaveEnter1);
	    net.addPrecondition(ready2, c2ToD2);
	    net.addPrecondition(d2, decouple2);
	    net.addPrecondition(decouples1, toD1);
	    net.addPrecondition(e2, toOut2);
	    net.addPostcondition(decouple2, dWait2);
	    net.addPrecondition(e1, toOut1);
	    net.addPrecondition(cWait2, toReady2);
	    net.addPostcondition(toOut1, out1);
	    net.addPostcondition(s2ToC2, preC2);
	    net.addPostcondition(d2ToE2, e2);
	    net.addPrecondition(c1, couple1);
	    net.addPrecondition(cWait2, toC2);
	    net.addPrecondition(decoupled2, d2ToE2_dec);
	    net.addPostcondition(toD2, d2);
	    net.addPostcondition(toReady1, ready1);
	    net.addPostcondition(toD1, d1);
	    net.addPrecondition(slaves1, slaveEnter1);
	    net.addPostcondition(slaveEnter1, sS1);
	    net.addPostcondition(couple2, cWait2);
	    net.addPostcondition(arrivals1, in1);
	    net.addPostcondition(d1ToE1, e1);
	    net.addPrecondition(cWait1, toC1);
	    net.addPrecondition(cWait1, toReady1);
	    net.addPostcondition(decouple1, dWait1);
	    net.addPrecondition(dWait1, d1ToE1);
	    net.addPrecondition(c2, couple2);
	    net.addPostcondition(decouple2, decoupled2);
	    net.addPrecondition(in2, slaveEnter2);
	    net.addPrecondition(decouples2, toD2);
	    net.addPrecondition(decoupled1, d1ToE1_dec);
	    net.addInhibitorArc(decoupled1, d1ToE1);
	    net.addPostcondition(d1ToE1_dec, e1_dec);
	    net.addPrecondition(e1_dec, toOut1_dec);
	    net.addPostcondition(toOut1_dec, out1);
	    net.addInhibitorArc(decoupled2, d2ToE2);
	    net.addPostcondition(d2ToE2_dec, e2_dec);
	    net.addPrecondition(e2_dec, toOut2_dec);
	    net.addPostcondition(toOut2_dec, out2);
	    net.addPostcondition(s1ToC1, preC1);
	    net.addPostcondition(preCouple1, c1);
	    net.addPrecondition(preC1, preCouple1);

	    //Generating Properties
	    marking.setTokens(c1, 0);
	    marking.setTokens(c2, 0);
	    marking.setTokens(cWait1, 0);
	    marking.setTokens(cWait2, 0);
	    marking.setTokens(couples1, 0);
	    marking.setTokens(couples2, 0);
	    marking.setTokens(d1, 0);
	    marking.setTokens(d2, 0);
	    marking.setTokens(dWait1, 0);
	    marking.setTokens(dWait2, 0);
	    marking.setTokens(decoupled1, 0);
	    marking.setTokens(decoupled2, 0);
	    marking.setTokens(decouples1, 0);
	    marking.setTokens(decouples2, 0);
	    marking.setTokens(e1, 0);
	    marking.setTokens(e1_dec, 0);
	    marking.setTokens(e2, 0);
	    marking.setTokens(e2_dec, 0);
	    marking.setTokens(in1, 0);
	    marking.setTokens(in2, 0);
	    marking.setTokens(out1, 0);
	    marking.setTokens(out2, 0);
	    marking.setTokens(preC1, 0);
	    marking.setTokens(preC2, 0);
	    marking.setTokens(ready1, 0);
	    marking.setTokens(ready2, 0);
	    marking.setTokens(sS1, 0);
	    marking.setTokens(sS2, 0);
	    marking.setTokens(sem, 1);
	    marking.setTokens(slaves1, 0);
	    marking.setTokens(slaves2, 0);
	    
	    arrivals1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal(t_arrival1), MarkingExpr.from("1", net)));
	    arrivals1.addFeature(new Priority(0));
	    arrivals2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal(t_arrival2), MarkingExpr.from("1", net)));
	    arrivals2.addFeature(new Priority(0));
	    c1ToD1.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_c1ToD1_eft), new BigDecimal(t_c1ToD1_lft)));
	    c2ToD2.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_c2ToD2_eft), new BigDecimal(t_c2ToD2_lft)));
	    couple1.addFeature(new EnablingFunction("c1>=2"));
	    couple1.addFeature(new PostUpdater("c1=0", net));
	    couple1.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_couple1_eft), new BigDecimal(t_couple1_lft)));
	    couple2.addFeature(new EnablingFunction("c2>=2"));
	    couple2.addFeature(new PostUpdater("c2=0", net));
	    couple2.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_couple2_eft), new BigDecimal(t_couple2_lft)));
	    d1ToE1.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_d1ToE1_eft), new BigDecimal(t_d1ToE1_lft)));
	    d1ToE1_dec.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_d1ToE1_eft), new BigDecimal(t_d1ToE1_lft)));
	    d2ToE2.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_d2ToE2_eft), new BigDecimal(t_d2ToE2_lft)));
	    d2ToE2_dec.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_d2ToE2_eft), new BigDecimal(t_d2ToE2_lft)));
	    decouple1.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_decouple1_eft), new BigDecimal(t_decouple1_lft)));
	    decouple2.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_decouple2_eft), new BigDecimal(t_decouple2_lft)));
	    preCouple1.addFeature(new EnablingFunction("c1+cWait1<2"));
	    preCouple1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    preCouple1.addFeature(new Priority(0));
	    preCouple2.addFeature(new EnablingFunction("c2+cWait2<2"));
	    preCouple2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    preCouple2.addFeature(new Priority(0));
	    masterEnter1.addFeature(new EnablingFunction("in1>=in2"));
	    masterEnter1.addFeature(new PostUpdater("slaves1=" + (getN()-1) + ",couples1=" + (getN()-2) + ",decouples1=" + (getN()-2), net));
	    masterEnter1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    masterEnter1.addFeature(new Priority(0));
	    masterEnter2.addFeature(new EnablingFunction("in2>=in1"));
	    masterEnter2.addFeature(new PostUpdater("slaves2=" + (getN()-1) + ",couples2=" + (getN()-2) + ",decouples2=" + (getN()-2), net));
	    masterEnter2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    masterEnter2.addFeature(new Priority(0));
	    s1ToC1.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_sS1ToC1_eft), new BigDecimal(t_sS1ToC1_lft)));
	    s2ToC2.addFeature(StochasticTransitionFeature.newUniformInstance(new BigDecimal(t_sS2ToC2_eft), new BigDecimal(t_sS2ToC2_lft)));
	    slaveEnter1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    slaveEnter1.addFeature(new Priority(0));
	    slaveEnter2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    slaveEnter2.addFeature(new Priority(0));
	    toC1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toC1.addFeature(new Priority(1));
	    toC2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toC2.addFeature(new Priority(1));
	    toD1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toD1.addFeature(new Priority(1));
	    toD2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toD2.addFeature(new Priority(0));
	    toOut1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toOut1.addFeature(new Priority(0));
	    toOut1_dec.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toOut1_dec.addFeature(new Priority(0));
	    toOut2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toOut2.addFeature(new Priority(0));
	    toOut2_dec.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toOut2_dec.addFeature(new Priority(0));
	    toReady1.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toReady1.addFeature(new Priority(0));
	    toReady2.addFeature(StochasticTransitionFeature.newDeterministicInstance(new BigDecimal("0"), MarkingExpr.from("1", net)));
	    toReady2.addFeature(new Priority(0));
	  }

}
